env:
  browser: true
  jquery : true
  node   : true
  es6    : true

extends:
  - airbnb/base

plugins:
  - babel

rules:
  indent:
    - 2
    - 4
  no-var: 1
  vars-on-top: 0
  func-names: 2
  prefer-const: 0
  comma-dangle: 0
  padded-blocks: 0
  no-floating-decimal: 0
  no-use-before-define: 0
  no-param-reassign: 0
  no-nested-ternary: 0 # Disallow Nested Ternaries
  func-names: 0 # Require Function Expressions to have a Name
  wrap-iife: 0
  dot-notation: 1
  no-multi-spaces:
    - 2
    - exceptions:
        ImportDeclaration : true
        VariableDeclarator: true
        AssignmentExpression: true
  no-unused-expressions:
    - 2
    -
      allowShortCircuit: true
      allowTernary: true
